baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'FKFs blog'
theme = 'ananke'


[params]
  text_color = ""
  author = "FKF"
  favicon = ""
  # site_logo = "https://geographical.co.uk/wp-content/uploads/panda1200-1.jpg"
  description = "FKFs personal rant site/blog"

  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-pink"


[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/fkf-studios"
